### ISSUE TITLE
What is this for?

### ISSUE THREAD

**Issue by stardust85** [att/python-music#1]
What is Music? Where is the content? It looks unprofessionally to leave such content here for one year. Can you please either add the content or delete the repo?

**Comment by jdandrea** [comment]
This project was shelved and the repo was being kept as a placeholder. Perhaps it can be hidden until such time that it is populated.

**Comment by gordonwoodhull** [comment]
I think since att is on the free plan, we can archive repos to make them read-only and clearly disabled, but we can't make them private. 

You can find Archive at the bottom of the Settings page for the project.

@stardust85, I think you'll find that there are a lot of inactive projects on GitHub. :wink:

**Comment by jdandrea** [comment]
@gordonwoodhull Thank you - apprecaited. Aye, archiving a project as nascent as this one doesn't seem worth it, huh.

According to the settings page, it's ostensibly possible to make it private but, if that isn't in fact the case, I'm perfectly fine with deleting it, as there's nothing here.
